services:
  postgres:
    image: "postgres:13"
    container_name: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=article
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=article
    networks:
      - app-network

  article-app:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile
    container_name: "article-app"
    restart: "always"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=article
      - DB_PASSWORD=example
      - DB_NAME=article
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

